### ISSUE TITLE
SSO因token过期等异常返回500状态码，在其它应用中浏览器会直接报500，在哪修改可以添加一个友好页面

### ISSUE THREAD

**Issue by DragonFlyEast** [NewLifeX/NewLife.Cube#92]
![CRJC1{AHDYVUEERX}MZUT3G](https://github.com/user-attachments/assets/ae1e77f7-3720-46b4-ba18-faba0ec3b0f6)
子应用也是用的newlife.cube，当开启sso时如果token过期了，此时刷新子应用就会直接500了，从哪拦截合适呢
谢谢！

**Comment by nnhy** [comment]
![image](https://github.com/user-attachments/assets/1be9a543-bd9b-4087-aa06-f4178f064d5c)
没有权限的页面是 NoPermission.cshtml ，可以在最终项目的Views/Shared 下覆盖

**Comment by nnhy** [comment]
token过期一般是提示无权限错误。
而/sso/LoginInfo 接口报500，大概率是程序异常，要看一下错误信息，然后让魔方处理这个问题。

**Comment by DragonFlyEast** [comment]
出现这种情况时魔方SSO日志中记录的是

```
08:38:59.075 106 Y TP System.ArgumentOutOfRangeException: Code已过期！ (Parameter 'code')
   at NewLife.Web.OAuthServer.GetToken(String code) in L:\NewLife\NewLife.Cube\NewLife.Cube\Web\OAuthServer.cs:line 243
   at NewLife.Cube.Web.SsoProvider.GetAccessToken(OAuthServer sso, String client_id, String client_secret, String code, String ip) in E:\NewLife\NewLife.Cube\NewLife.Cube\Web\SsoProvider.cs:line 575
   at NewLife.Cube.Controllers.SsoController.Access_Token(String client_id, String client_secret, String code, String grant_type) in E:\NewLife\NewLife.Cube\NewLife.CubeNC\Controllers\SsoController.cs:line 499

#Software: 魔方用户中心
#ProcessID: 1053388 x64
#AppDomain: CubeSSO
```

**Comment by nnhy** [comment]
需要修改这里的代码，捕获异常后，返回异常页面

**Comment by nnhy** [comment]
// 使用自己的异常处理页，后续必须再次UseRouting
            if (!env.IsDevelopment())
                app.UseExceptionHandler("/CubeHome/Error");

刚翻了代码，异常处理页是这个，对应视图 ~/Views/Shared/Error.cshtml，你可以覆盖这个。

**Comment by nnhy** [comment]
遇到异常时，魔方响应500代码，并输出Error.cshtml。一般的反向代理会拦截500，替换为自己的页面。
