### ISSUE TITLE
希望可以捕获数据库异常，不让程序退出。

### ISSUE THREAD

**Issue by gBelieve** [NewLifeX/NewLife.Cube#98]
03:11:00.205 86 Y P XCode.Exceptions.XDbSessionException: database is locked
database is locked[DB:Membership/SQLite]
 ---> code = Busy (5), message = System.Data.SQLite.SQLiteException (0x87AF00AA): database is locked
database is locked
   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, SQLiteCommand command, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteConnection.Open()
   at XCode.DataAccessLayer.DbBase.OpenConnection()
   at XCode.DataAccessLayer.Transaction.Begin()
   at XCode.DataAccessLayer.DbSession.BeginTransaction(IsolationLevel level)
   --- End of inner exception stack trace ---
   at XCode.DataAccessLayer.DbSession.BeginTransaction(IsolationLevel level)
   at XCode.EntityTransaction`1..ctor()
   at NewLife.Cube.Services.MyJob.CheckRunning(CronJob job)
   at NewLife.Cube.Services.MyJob.DoJobWork(Object state)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
03:11:00.206 86 Y P 异常退出！
03:11:01.001 84 Y T [Membership] Select * From CronJob Where Id=5
03:11:01.001 84 Y T [Membership] Update CronJob Set LastTime='2024-10-31 03:11:01.0014195',UpdateTime='2024-10-31 03:11:00.8115548' Where Id=5

**Comment by nnhy** [comment]
DoJobWork方法声明为 async void DoJobWork，导致内部无法捕获异常，修改为 async Task DoJobWork 即可
